### ISSUE TITLE
Problem about add new heterogenous reaction in KPP, no reaction production

### ISSUE THREAD

**Issue by LianHeng-Li** [geoschem/KPP#2]
I try to add a new heterogenous reaction in KPP, but seem useless. Because the product species concentration seems no change after I add this reaction.

I followed the add reaction steps in KPP by https://kpp.readthedocs.io/., and I had add the equation in Custom.eqn also the reaction in HetRates and rebuild the KPP by ./build_mechanism.sh custom.  But the production concentration still seems no change.

**Comment by Li-Yumin** [comment]
![image](https://user-images.githubusercontent.com/75835812/113721314-0005e280-9722-11eb-86ef-08bacc107ca8.png)
all the productions I add looks in the same concentration ranged in 10^(-2)  it seems no production be added in.

**Comment by yantosca** [comment]
Thanks for writing.  We need more information before we can give you advice.  Are you using the heterogeneous reactions in GEOS-Chem?  Can you attach the .eqn and .kpp files to this issue (rename them to .eqn.txt and .kpp.txt,and drag and drop here).

**Comment by Li-Yumin** [comment]
I think  I didn't make any changes to the gckpp.KPP file

In the .eq file. I add this:
![image](https://user-images.githubusercontent.com/75835812/113806218-7f33fe80-9794-11eb-8737-37ed24221b36.png)
![image](https://user-images.githubusercontent.com/75835812/113806295-9d016380-9794-11eb-8da4-99cf1c0c3461.png)
I just want to add back the SOAMG to separate the SOA generate from glyoxal and methlyglyoxal.

**Comment by Li-Yumin** [comment]
The problem seems to be with Rebuild KPP, because when I compare the rebuild KPP and the  original document I find this different:
![image](https://user-images.githubusercontent.com/75835812/113827155-8ddedd80-97b5-11eb-962d-a494b089e17f.png)
The orignial build by kpp-2.2.4 and now I download from website si kpp-2.3.1
and also in the gckpp.map, there are seems missing use one subroutine  "Fun (V, F, RCT, Vdot)"
The original gckpp.map:
![image](https://user-images.githubusercontent.com/75835812/113827626-18bfd800-97b6-11eb-85e4-e7b207f048f0.png)

the rebuild gckpp.map:
![image](https://user-images.githubusercontent.com/75835812/113827525-fe85fa00-97b5-11eb-94c0-a250d628d8ac.png)

**Comment by yantosca** [comment]
Thanks for writing.  If you are using a GEOS-Chem version older than 13.0.0, you should try using the prior KPP version (KPP 2.2.4_gc).  You can clone that with:

```
git clone -b 2.2.4_gc https://github.com/geoschem/KPP.git
```

In the near future we hope to add KPP as a submodule within GEOS-Chem, so that there will not be any version mismatches between KPP and GEOS-Chem.

**Comment by Li-Yumin** [comment]
Dear yantosca,

Thank you for your help,  I tried using the version of the code you provided, and now the problem has been solved!

**Comment by yantosca** [comment]
Thanks for the feedback!  I'll close this issue out.
